[package]
edition.workspace = true
name = "kith-vcard"
version.workspace = true

[dependencies]
calcard = "0.3.2"
chrono = { workspace = true }
kith-core = { path = "../kith-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
